services:
  qwentyn.api_core.response:
    class: QuentinMachard\ApiCoreBundle\Api\ApiResponse
    arguments: ['@jms_serializer.serializer']
  qwentyn.api_core.form_processor:
    class: QuentinMachard\ApiCoreBundle\Processor\FormProcessor
  qwentyn.api_core.exception_subscriber:
    class: QuentinMachard\ApiCoreBundle\EventListener\ApiExceptionSubscriber
    tags:
      - { name: kernel.event_subscriber }
    arguments: ['@kernel', '@qwentyn.api_core.response', '@logger']